language: python

matrix:
  include:
  # todo update versions
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: 3.12

install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -vv -Ue .

script:
  make cov-report

after_success:
  codecov
