language: python
sudo: required


python:
  - '3.5'
  - '3.6'

install:
  - pip install --upgrade setuptools
  - pip install codecov
  - pip install -r requirements-dev.txt
  - make install

script:
  make cov-report
after_success:
  codecov
