language: python
sudo: required

matrix:
  include:
    - python: "3.6"
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
    - python: "pypy3"

install:
  - pip install --upgrade setuptools
  - pip install codecov
  - pip install -r requirements-dev.txt
  - pip install -vv -Ue .

script:
  make cov-report
after_success:
  codecov
