language: python
sudo: required

python:
  - '3.5'
  - '3.6'
  - 'pypy3.5'

install:
  - pip install --upgrade setuptools
  - pip install codecov
  - pip install -r requirements-dev.txt
  - pip install -vv -Ue .

script:
  make cov-report
after_success:
  codecov
